### PR TITLE
Fix SparseOutputSpec test

### PR DESCRIPTION
**Pull request by raronson**
@charleso @nhibberd Some values are empty strings, and `EavtParsers.splitLine` calls `String.split` without `-1`.

### CODE REVIEW

**Comment by charleso** [comment]
:+1:

**Comment by markhibberd** [comment]
It is doing an additional check that it is exactly 4 fields. I can't tell from the context of this, is it EAVT or is it somthing that happens to be 4 fields. If it is EAVT, why is time empty I guess?

**Comment by raronson** [comment]
> is it EAVT or is it somthing that happens to be 4 fields

Its EAV (without time) but namespace and attribute are in two columns. Its the sparse output job - https://github.com/ambiata/ivory/blob/master/ivory-operation/src/main/scala/com/ambiata/ivory/operation/extraction/output/SparseOutputJob.scala#L136-L142

**Comment by markhibberd** [comment]
:+1:

**Pull request merged**
